name: flutter_application_mobiletest2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  qr_flutter: ^4.0.0
  quiver: ^3.2.1
  flutter_timer_countdown: ^1.0.5
  file_picker: ^4.0.0
  flutter_session_manager: ^1.0.3
  path_provider: ^2.0.13
  dio: ^5.3.2
  shared_preferences: ^2.0.12
  qr_code_scanner: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  quickalert: ^1.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
